### ISSUE TITLE
Kernel actions result in uncaught exception

### ISSUE THREAD

**Issue by odewahn** [rgbkrk/kernels-service#2]
I'm trying the various functions on the just_the_kernels branch, and kernel actions (restart or interrupt) seem to be throwing uncaught exceptions.  For example, hitting this endpoint:

http://192.168.59.103:8000/api/kernels/27535e31-6b5e-48f0-b493-e92dc5548ac9/restart

Throws this error:

[E 150111 01:57:17 web:931] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1332, in _execute
        result = method(_self.path_args, *_self.path_kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 212, in get
        raise HTTPError(405)
    tornado.web.HTTPError: HTTP 405: Method Not Allowed

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 929, in send_error
    self.write_error(status_code, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/base/handlers.py", line 293, in write_error
    html = self.render_template('%s.html' % status_code, **ns)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/base/handlers.py", line 234, in render_template
    template = self.get_template(name)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/base/handlers.py", line 230, in get_template
    return self.settings['jinja2_env'].get_template(name)
KeyError: 'jinja2_env'
```

**Comment by rgbkrk** [comment]
I'm seeing this too, definitely looks like there is more to decouple if we want a pure kernels API.

```
$ python kernels.py --base-path=ew5
[I 150113 21:40:28 kernelmanager:85] Kernel started: 309d5a7b-83b5-4a3d-b390-7895c880f061
[I 150113 21:40:28 kernels:102] Serving at http://127.0.0.1:8000/ew5/api/kernels
[I 150113 21:40:43 web:1811] 200 GET /ew5/api/kernels (127.0.0.1) 1.12ms
[I 150113 21:40:51 web:1811] 200 GET /ew5/api/kernels/309d5a7b-83b5-4a3d-b390-7895c880f061 (127.0.0.1) 0.52ms
[E 150113 21:40:55 web:931] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 929, in send_error
        self.write_error(status_code, **kwargs)
      File "/Users/kyle6475/code/ipython/IPython/html/base/handlers.py", line 293, in write_error
        html = self.render_template('%s.html' % status_code, **ns)
      File "/Users/kyle6475/code/ipython/IPython/html/base/handlers.py", line 234, in render_template
        template = self.get_template(name)
      File "/Users/kyle6475/code/ipython/IPython/html/base/handlers.py", line 230, in get_template
        return self.settings['jinja2_env'].get_template(name)
    KeyError: 'jinja2_env'
[W 150113 21:40:55 web:1811] 405 GET /ew5/api/kernels/309d5a7b-83b5-4a3d-b390-7895c880f061/restart (127.0.0.1) 2.23ms
```

**Comment by rgbkrk** [comment]
Sure enough, it's trying to produce an error page but it wants to show a full HTML error page instead of JSON. This ends up needing templates. I'll submit a PR for this on the kernels service and then possibly submit another PR upstream to decouple the kernels a bit more.

**Comment by rgbkrk** [comment]
The kernel actions should be a POST instead of a GET with IPython 3.0.
